# Generated by Django 4.0.3 on 2022-03-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_user_number_of_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_address',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
