# Generated by Django 4.0.3 on 2022-03-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_caregory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='caregory',
            new_name='category',
        ),
    ]
